# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # develop branch
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/server"
    schedule:
      interval: "weekly"

  # next branch
  - package-ecosystem: "npm"
    directory: "/client"
    target-branch: "next"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/server"
    target-branch: "next"
    schedule:
      interval: "daily"
